services:
  preboot_lander:
    build:
      context: .
#      args:
#        INSTALL_DEBUGPY: "True"
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    external: true
    name: nprp_net
